#!/bin/bash
# Aoo Create Perl encripted Password # Version 1.0.0.1
# Script Developed by Apivat Pattana-Anurak
# SysAdmin & Programmer Form #Bangkok #Thailand 

$ password=" ! your password " // กำหนดรหัสผ่าน
$ pass=$(perl -e 'print crypt($ARGV[0], "password")' $password) // แปลงรหัสผ่านเป็น perl encrypted
$ echo $pass // ประการตัวแปล ให้แสดงเป็นรหัส encrypted
