#!/bin/bash
# Aoo Basic Remove Account wrapper # Version 1.0.0.1
# Aoo installation wrapper script by Aoo Studio
# Script Developed by Apivat Pattana-Anurak
# SysAdmin & Programmer # Thailand # Bangkok
# https://www.aoostudio.com

rm -R /home/aoo/.ssh
